repos:
  - repo: local
    hooks:
      - id: backend-pre-commit
        name: Run backend pre-commit hooks
        entry: bash -c 'cd backend && uv run pre-commit run --all-files --config=.pre-commit-config.yaml'
        language: system
        pass_filenames: false
        always_run: true
        stages: [ pre-commit, pre-push, manual ]
        verbose: true
  - repo: local
    hooks:
      - id: frontend-pre-commit
        name: Run frontend pre-commit hooks
        entry: bash -c 'cd frontend && npm run check'
        language: system
        pass_filenames: false
        always_run: true
        stages: [ pre-commit, pre-push, manual ]
        verbose: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.38.0
    hooks:
      - id: eslint
  - repo: https://github.com/pylint-dev/pylint
    rev: v2.17.2
    hooks:
      - id: pylint
